# Generated by Django 4.1.1 on 2022-09-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_route_route_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField()),
                ('review', models.TextField()),
                ('review_rate', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('car', 'car'), ('foot', 'foot'), ('bicycle', 'bicycle')], default='foot', max_length=10),
        ),
    ]
