# Generated by Django 4.1.1 on 2022-10-24 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_event_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approved_user',
        ),
        migrations.RemoveField(
            model_name='event',
            name='pending_user',
        ),
        migrations.AddField(
            model_name='event',
            name='event_users',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='stopping_point',
            field=models.CharField(max_length=50),
        ),
    ]
